version: '3.8'

services:
  mysqldb:
    image: mysql:8.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=fullstackuser
      - MYSQL_PASSWORD=fullstackpwd
      - MYSQL_DATABASE=fullstackdb
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - "./database/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./database/data.sql:/docker-entrypoint-initdb.d/2.sql"

  backend:
    build: ./rest-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_HOST=mysqldb
    depends_on:
      - mysqldb

  frontend:
    build:
      context: ./frontend
      target: dev
    # environment:
    #   NODE_ENV: production
    ports:
      - 5173:5173
      - 9229:9229
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
