server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/fullstackdb
    username: ${MYSQL_USER:fullstackuser}
    password: ${MYSQL_PASSWORD:fullstackpwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
